const login=document.getElementById("login"),meter=document.getElementById("meter"),loginError=document.getElementById("loginError"),meterError=document.getElementById("meterError");
const escapeText=v=>String(v??"").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
async function api(path,options={}){const response=await fetch(path,options);let data={};try{data=await response.json()}catch(_){ }if(!response.ok)throw Error(data.error||"Request failed");return data}
function showError(el,error){el.textContent=error?.message||String(error)}
async function load(){try{const me=await api("/api/user/me");login.classList.add("hidden");meter.classList.remove("hidden");document.getElementById("accountName").textContent=me.account?.access_key_id||"Account";document.getElementById("accountId").textContent=me.account?.account_id||"--";await refresh()}catch(_){login.classList.remove("hidden");meter.classList.add("hidden")}}
async function refresh(){meterError.textContent="";document.getElementById("usage").innerHTML='<div class="loading">Loading usage...</div>';document.getElementById("requests").innerHTML='<div class="loading">Loading requests...</div>';try{const balance=await api("/api/user/balance"),b=balance.balance||{};document.getElementById("balance").textContent=b.available_balance||b.balance||"0";document.getElementById("currency").textContent=b.currency||"";document.getElementById("updated").textContent=new Date().toLocaleTimeString();const bucket=document.getElementById("bucket").value;const usage=await api("/api/user/usage?bucket="+encodeURIComponent(bucket));renderUsage(usage.rows||[]);const requests=await api("/api/user/requests");renderRequests(requests.requests||[])}catch(error){showError(meterError,error);document.getElementById("usage").innerHTML=""}}
function renderUsage(rows){if(!rows.length){document.getElementById("usage").innerHTML='<div class="loading">No usage recorded for this window.</div>';return}document.getElementById("usage").innerHTML='<div class="usage-grid">'+rows.map(row=>{const d=row.dimensions||{},m=row.measures||{};return '<article class="usage-card"><h3>'+escapeText(d.model||"All models")+'</h3><strong>'+escapeText(m.quantity||"0")+'</strong><small>'+escapeText(d.bucket||"")+'</small></article>'}).join("")+"</div>"}
function renderRequests(rows){if(!rows.length){document.getElementById("requests").innerHTML='<div class="loading">No requests recorded for this window.</div>';return}document.getElementById("requests").innerHTML=rows.map(row=>'<div class="request-row"><small>'+escapeText(row.occurred_at?new Date(row.occurred_at*1000).toLocaleString():"--")+'</small><span>'+escapeText(row.model||"Model unavailable")+'</span><small>'+escapeText(row.request_id||"Request unavailable")+'</small></div>').join("")}
document.getElementById("loginForm").addEventListener("submit",async event=>{event.preventDefault();loginError.textContent="";try{await api("/api/user/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({access_key:document.getElementById("accessKey").value})});document.getElementById("accessKey").value="";await load()}catch(error){showError(loginError,error)}});
document.getElementById("logout").onclick=async()=>{await api("/api/user/logout",{method:"POST"});load()};document.getElementById("refresh").onclick=refresh;document.getElementById("bucket").onchange=refresh;load();
